; Auto-generated by build-exe.ps1
; Karpathy-Wiki Inno Setup 配置
#ifndef MyAppVersion
  #define MyAppVersion "0.1.0"
#endif
[Setup]
AppName=Karpathy-Wiki
AppVersion={#MyAppVersion}
AppPublisher=Karpathy-Wiki
DefaultDirName={autopf}\KarpathyWiki
DefaultGroupName=KarpathyWiki
UninstallDisplayIcon={app}\karpathy-wiki.exe
OutputDir=dist
OutputBaseFilename=KarpathyWiki-Setup-v{#MyAppVersion}
Compression=lzma2
SolidCompression=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=admin
DisableProgramGroupPage=yes
[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
[Tasks]
Name: "desktopicon"; Description: "创建桌面快捷方式"; GroupDescription: "附加选项:"
[Files]
Source: "dist\karpathy-wiki\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
[Icons]
Name: "{group}\Karpathy-Wiki"; Filename: "{app}\karpathy-wiki.exe"
Name: "{commondesktop}\Karpathy-Wiki"; Filename: "{app}\karpathy-wiki.exe"; Tasks: desktopicon
[Run]
Filename: "{app}\karpathy-wiki.exe"; Description: "启动 Karpathy-Wiki"; Flags: nowait postinstall skipifsilent