
import sys
sys.stdout.reconfigure(encoding="utf-8")
B = chr(96)
D = chr(36)
NL = chr(10)
Q = chr(39)
DQ = chr(34)
BS = chr(92)

L = []
def a(s):
    L.append(s)

# Header
a("// URL 爬取核心工具：BFS 遍历 + 路径前缀限制 + 三跳限制 + 附件识别")
a("")
a("// 优化实施（5.x 系列）：")
a("// - 5.1.1+5.5.1+5.5.2 robots.txt 解析与 Crawl-delay 遵循")
a("// - 5.1.2 并发控制：同深度页面 Promise 池")
a("// - 5.2.1 模板噪声过滤可配置化")
a("// - 5.2.3 附件类型智能过滤")
a("// - 5.2.5 附件跨页面去重")
a("// - 5.3.1 重试机制：指数退避")
a("// - 5.3.3 爬取日志持久化")
a("// - 5.3.4 超时分级")
a("// - 5.4.4 耗时显示")
a("// - 5.5.3 版权声明")
a("")
a("import { type UrlCrawlConfig, type UrlCrawlEvent, type UrlCrawlPage, type UrlCrawlAttachment } from '../types.js';")
a("import fs from 'node:fs/promises';")
a("import path from 'node:path';")
a("")
a("const DEFAULT_CRAWL_CONFIG: Required<UrlCrawlConfig> = {")
a("  maxHops: 3, timeoutMs: 10000, maxPages: 50,")
a("  userAgent: " + Q + "KarpathyWikiBot/1.0" + Q + ",")
a("  allowedAttachmentTypes: ['pdf','doc','docx','xls','xlsx','ppt','pptx','jpg','jpeg','png','gif','webp','svg','mp4','webm','mp3','wav','ogg'],")
a("  followRobotsTxt: true, crawlDelayMs: 0, concurrency: 1,")
a("  excludeTemplateElements: true, renderJs: false,")
a("  contentAttachmentTypes: ['pdf','doc','docx','xls','xlsx','ppt','pptx','mp4','webm','mp3','wav','ogg'],")
a("  retryAttempts: 1, retryBackoffMs: 500, enableAttachmentDedup: true,")
a("  logging: { enabled: false, logFilePath: '../data/url-crawl.log' },")
a("  connectTimeoutMs: 0, readTimeoutMs: 0,")
a("  copyrightNotice: " + Q + "本文内容来源于互联网公开资源，仅用于个人知识管理，如有侵权请联系删除" + Q + ",")
a("  preserveOnCancel: true,")
a("};")
a("")

# SSRF check
a("async function checkSSRF(urlStr) {")
a("  const hostname = new URL(urlStr).hostname;")
a("  try {")
a("    const dns = await import(" + Q + "node:dns" + Q + ");")
a("    const ipv4s = await dns.promises.resolve4(hostname);")
a("    for (const addr of ipv4s) {")
a("      if (/^10\\./.test(addr) || /^172\\.(1[6-9]|2[0-9]|3[01])\\./.test(addr) || /^192\\.168\\./.test(addr) || /^127\\./.test(addr)) {")
a(f'        throw new Error({B}SSRF blocked: hostname "{D}{{hostname}}" resolves to private IP: {D}{{addr}}{B});')
a("      }")
a("    }")
a("  } catch {}")
a("}")
a("")

# Parse robots
a(f"Bexport function parseRobotsTxt(raw: string): RobotsTxt {B}")
a(f"B  const lines = raw.split(BnB);{B}")
a("  const rules: RobotsRule[] = [];")
a("  let crawlDelaySec = 0;")
a("  let currentUserAgents: string[] = [];")
a("  let inOurBlock = false;")
a("  const ROBOTS_BOT_NAME = " + Q + "KarpathyWikiBot" + Q + ";")
a("  for (const rawLine of lines) {")
a("    const line = rawLine.split(" + Q + "#" + Q + ")[0].trim();")
a("    if (!line) continue;")
a("    const colonIdx = line.indexOf(" + Q + ":" + Q + ");")
a("    if (colonIdx < 0) continue;")
a("    const directive = line.slice(0, colonIdx).trim().toLowerCase();")
a("    const value = line.slice(colonIdx + 1).trim();")
a("    if (directive === " + Q + "user-agent" + Q + ") {")
a("      currentUserAgents.push(value.toLowerCase());")
a("      inOurBlock = currentUserAgents.some((ua) => ua === " + Q + "*" + Q + " || ua === ROBOTS_BOT_NAME.toLowerCase());")
a("      continue;")
a("    }")
a("    if (inOurBlock) {")
a("      if (directive === " + Q + "allow" + Q + ") rules.push({ pattern: value, allow: true });")
a("      else if (directive === " + Q + "disallow" + Q + " && value !== " + Q + Q + ") rules.push({ pattern: value, allow: false });")
a("      else if (directive === " + Q + "crawl-delay" + Q + ") {")
a("        const parsed = parseInt(value, 10);")
a("        if (!Number.isNaN(parsed) && parsed > 0) crawlDelaySec = parsed;")
a("      }")
a("    }")
a("    if (directive !== " + Q + "user-agent" + Q + ") { currentUserAgents = []; inOurBlock = false; }")
a("  }")
a("  return { rules, crawlDelaySec, fetched: true };")
a("}")

with open(pathFull, "w", encoding="utf-8") as f:
    f.write(NL.join(L) + NL)

print(f"Wrote first part: {len(L)} lines")
