import Fastify from 'fastify';
import fastifyStatic from '@fastify/static';
import compress from '@fastify/compress';
import fs from 'node:fs';
fs.mkdirSync('C:/tmp/kwstatic', { recursive: true });
fs.writeFileSync('C:/tmp/kwstatic/index.html', '<html>hi</html>');
const app = Fastify();
await app.register(fastifyStatic, { root: 'C:/tmp/kwstatic', prefix: '/', wildcard: false, decorateReply: false });
await app.register(compress, { threshold: 1024, encodings: ['br','gzip','deflate'] });
app.get('/big', async () => ({ data: 'x'.repeat(2000) }));
await app.listen({ port: 4300, host:'127.0.0.1' });
const res = await fetch('http://127.0.0.1:4300/big', { headers:{ 'Accept-Encoding':'gzip' } });
const buf = Buffer.from(await res.arrayBuffer());
console.log('static+compress ce='+res.headers.get('content-encoding')+' cl='+res.headers.get('content-length')+' bodyLen='+buf.length);
await app.close(); process.exit(0);
