import Fastify from 'fastify';
import compress from '@fastify/compress';
const app = Fastify();
await app.register(compress, { threshold: 1024, encodings: ['br','gzip','deflate'] });
app.get('/big', async () => ({ totalPages:183, totalLinks:390, dirCounts:{entities:53,concepts:103}, recentLog:'绑定问答，建立相关实体页面（综服平台、交易系统、CPP014002、CPP001002），抽取实体关系，状态改为published\n\n## 2026-07-29 09:19\n- 操作类型：compile' }));
await app.listen({ port: 4200, host:'127.0.0.1' });
const res = await fetch('http://127.0.0.1:4200/big', { headers:{ 'Accept-Encoding':'gzip' } });
const buf = Buffer.from(await res.arrayBuffer());
console.log('CN ce='+res.headers.get('content-encoding')+' cl='+res.headers.get('content-length')+' bodyLen='+buf.length);
await app.close(); process.exit(0);
