sonar.projectKey=karpathy_wiki_api
sonar.projectName=Karpathy Wiki API
sonar.sources=src
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/coverage/**
sonar.typescript.node=D:\tools\nodejs\node.exe
sonar.scm.disabled=true